spring.application.name=shiftlog
spring.profiles.default=mnarongo
shiftlog.gui.enabled=${SHIFTLOG_GUI_ENABLED:true}
springdoc.swagger-ui.path=/swagger-ui.html
server.max-http-request-header-size=64KB
